[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_props = "g64EtQutPeM1tB3d16LWZzBryhT27G2g16pyHVUhXVS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
